Email marketing
kempsterrrr/P3RKS pull request #90
Opened 2022-12-06 20:11 UTC by kempsterrrr

## Describe your changes

- Created custom `/verify-request` page
- introduce local email templates

No DB changes. No analytics events.

## Issue ticket number and link

NA

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I've included any relevant links to DB changes/deploy-requests
- [x] I've added any required Analytics events

2022-12-06 21:36 UTC, mbuxmann requested changes

2022-12-06 21:36 UTC, mbuxmann commented on .nvmrc
> +v18.12.0
I assume since we aren't using postmark sdk anymore we bumping this up to 18 again?

2022-12-06 21:36 UTC, mbuxmann commented on src/pages/api/auth/[...nextauth].ts
> +}) {
```
async function CustomSendVerificationRequest(params: {
  identifier: string;
  url: string;
  provider: any;
})
```

2022-12-06 21:36 UTC, mbuxmann commented on src/pages/api/auth/[...nextauth].ts
> +}) {
I'm sure a provider has a type we can find. We should try and avoid any at all costs.

2022-12-06 21:36 UTC, mbuxmann commented on src/pages/api/auth/[...nextauth].ts
> +  const { identifier, url, provider, theme } = params;
theme can be removed

2022-12-06 21:36 UTC, mbuxmann commented on src/pages/api/auth/[...nextauth].ts
> +function html(params: { url: string; host: string; theme: Theme }) {
remove theme

2022-12-06 21:36 UTC, mbuxmann commented on src/pages/api/auth/[...nextauth].ts
> +  const { url, host, theme } = params;
remove theme

2022-12-06 21:37 UTC, mbuxmann commented on src/pages/api/auth/[...nextauth].ts
> +}) {
if not just add a note so we can look into it later. 

`// TODO(refactor): Add provider type`

2022-12-06 21:40 UTC, mbuxmann approved these changes
LGTM, just some recommended changes 👍🏻

2022-12-07 15:14 UTC, kempsterrrr commented on src/pages/api/auth/[...nextauth].ts
> +}) {
Found it ! EmailConfig

Should the URL type be URL?

2022-12-07 15:16 UTC, kempsterrrr commented
Update, let one comment regarding URL vs String type

2022-12-07 15:18 UTC, kempsterrrr commented
Oooops. Think I might have fucked up by merging in staging locally 🤦🏻 cc @mbuxmann

2022-12-07 15:26 UTC, mbuxmann commented on src/pages/api/auth/[...nextauth].ts
> +}) {
no string is fine. it seems like it does convert it for you to a URL below `const { host } = new URL(url);`

2022-12-08 01:46 UTC, kempsterrrr commented on src/pages/api/auth/[...nextauth].ts
> +}) {
awesome, thanks

2022-12-08 01:46 UTC, kempsterrrr commented on .nvmrc
> +v18.12.0
Yup works fine for me

2022-12-08 01:46 UTC, merged